# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
before_install:
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'