on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Linux setup
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install jags
          
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
      
      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
